---
- hosts: jenkins-nodes
  strategy: free
  gather_facts: no
  become: true
  tasks:
    - name: install apt deps
      apt:
        name:
          - jq
          - make
          - curl
          - wget
          - docker.io
          - unzip
          - python3-pip
          - flake8
          - python-pip
          - squashfuse
          - snapd
          - snapcraft
          - libffi6
          - libffi-dev
          - libssl-dev
          - default-jre
    - name: remove deb lxd
      apt:
        name:
          - lxd
          - lxd-client
          - lxcfs
          - lxc-common
          - liblxc1
        state: absent
    - name: update ubuntu user
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: install snap deps
      command: "snap install {{item}}"
      loop:
        - "lxd"
        - "juju --classic"
        - "juju-wait --classic"
        - "kubectl --classic"
        - "charm --edge --classic"
    - name: setup lxd network
      command: "/snap/bin/lxd init --auto"
    - name: initialize snap directories
      command: "/snap/bin/{{item}} version"
      become: false
      loop:
        - juju
        - charm
    - name: update ubuntu groups
      user:
        name: ubuntu
        groups: lxd
        append: yes
    - name: create charm/snap folders
      file:
        path: "/home/ubuntu/{{item}}"
        state: directory
      loop:
        - .local/share/juju
        - snap/charm/current/.local/share/juju
    - name: copy data files
      synchronize:
        src: /var/lib/jenkins/.local/share/juju
        dest: /home/ubuntu/.local/share
        dirs: yes
        rsync_opts:
          - "--exclude=jclient"
          - "--exclude=charmcache"
          - "--exclude=.deployer-store-cache"
    - name: copy aws files
      synchronize:
        src: /var/lib/jenkins/.aws
        dest: /home/ubuntu/
        dirs: yes
    - name: copy data files
      copy:
        src: /var/lib/jenkins/.go-cookies
        dest: /home/ubuntu/.go-cookies
        mode: u=r
    - name: copy store usso token
      copy:
        src: /var/lib/jenkins/.local/share/juju/store-usso-token
        dest: /home/ubuntu/snap/charm/current/.local/share/juju/store-usso-token
        mode: u=r

    - name: set perms
      file:
        path: /home/ubuntu/{{item}}
        owner: ubuntu
        group: ubuntu
        recurse: yes
      loop:
        - .local/share/juju
        - snap
        - .aws
    - name: update juju credentials path
      replace:
        path: /home/ubuntu/.local/share/juju/credentials.yaml
        regexp: '.*file:(.*)$'
        replace: '      file: /home/ubuntu/.local/share/juju/foo.json'
