---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: install apt deps
      apt:
        name:
          - apache2
          - apt-mirror
          - simplestreams
          - squid
      tags:
        - enable
    - name: remove unused debs
      apt:
        name:
          - juju
          - lxd
          - lxd-client
          - lxcfs
          - lxc-common
          - liblxc1
        state: absent
      tags: enable
    - name: install snap deps
      command: "snap install {{item}}"
      ignore_errors: yes
      loop:
        - "juju --channel=3/stable"
        - "juju-wait --classic"
        - "lxd"
      tags:
        - enable
    - name: update ubuntu user
      user:
        name: ubuntu
        groups: lxd
      tags:
        - enable
    - name: reset ssh connection
      meta: reset_connection
      tags:
        - enable
    - name: setup lxd network
      command: "/snap/bin/lxd init --auto"
      ignore_errors: yes
      become: false
      tags:
        - enable
    - name: disable ipv6 in lxd
      become: false
      shell: |
        export PATH=/snap/bin:$PATH
        lxc network set lxdbr0 ipv6.address none
      ignore_errors: true
      tags:
        - enable
    - name: import local lxd images
      become: false
      shell: |
        export PATH=/snap/bin:$PATH
        lxc image copy ubuntu:18.04 local: --copy-aliases
        lxc image copy ubuntu:16.04 local: --copy-aliases
        lxc image copy ubuntu:14.04 local: --copy-aliases
      tags:
        - enable

    - name: copy mirror list
      copy:
        src: "fixtures/apt-mirror.list"
        dest: /etc/apt/mirror.list
        owner: root
        group: root
        mode: 0644
        force: yes
      tags:
        - enable

    - name: setup apache mirror
      copy:
        src: "fixtures/ubuntu-mirror.conf"
        dest: /etc/apache2/sites-available/ubuntu-mirror.conf
        owner: root
        group: root
        mode: 0644
        force: yes
      tags:
        - enable
    - name: enable mirror site
      shell: |
        a2ensite ubuntu-mirror.conf
        systemctl restart apache2
        apt-mirror
      tags:
        - enable
    - name: setup simplestreams
      shell: |
        export WORKDIR=/var/spool/sstreams/juju
        sudo sstream-mirror --no-verify --progress --max=1 \
          --path=streams/v1/index2.sjson \
          https://streams.canonical.com/juju/tools/ \
          $WORKDIR 'arch=amd64' 'release~(xenial|bionic)' 'version~(2.2|2.3|2.4|2.5|2.6)'

        export WORKDIR=/var/spool/sstreams/lxdkvm
        sudo sstream-mirror --keyring=/usr/share/keyrings/ubuntu-cloudimage-keyring.gpg \
          --progress --max=1 --path=streams/v1/index.json \
          https://cloud-images.ubuntu.com/releases/ \
          $WORKDIR/_latest 'arch=amd64' 'release~(xenial|bionic)' \
          'ftype~(lxd.tar.xz|squashfs|root.tar.xz|root.tar.gz|disk1.img|.json|.sjson)'
      tags:
        - enable
    - name: set pki dirs
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      loop:
        - /etc/pki/tls/private/
        - /etc/pki/tls/certs/
      tags:
        - enable
    - name: copy ssl conf
      template:
        src: "fixtures/ssl.conf.j2"
        dest: "/root/ssl.conf"
      tags:
        - enable
    - name: setup ssl for juju metadata
      shell: |
        openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 \
          -config /root/ssl.conf \
          -keyout /etc/pki/tls/private/mirror.key \
          -out /etc/pki/tls/certs/mirror.crt
      tags:
        - enable
    - name: enable sstreams site
      shell: |
        a2enmod ssl
        a2ensite sstreams-mirror.conf
        systemctl restart apache2
      tags:
        - enable
    - name: setup squid
      template:
        src: "fixtures/squid.conf.j2"
        dest: "/etc/squid/squid.conf"
      tags:
        - enable
    - name: setup cloudinit userdata
      template:
        src: "fixtures/cloudinit.yaml.j2"
        dest: "/home/ubuntu/cloudinit-userdata.yaml"
      become: no
      tags:
        - enable
    - name: update /etc/environment
      copy:
        src: "fixtures/environment"
        dest: /etc/environment
        owner: root
        group: root
        mode: 0644
        force: yes
      tags:
        - enable

    - name: disable squid
      shell: |
        systemctl stop squid
      tags:
        - disable
